services:
  arma-reforger-service:
    #image: ghcr.io/nhimself/docker-reforger:latest
    image: docker-reforger:latest
    platform: linux/amd64
    container_name: arma-reforger-server
    secrets: 
      - admin_password
      - user_password
      - rcon_password
    deploy: # please adjust to fit your environment
          resources: 
            limits:
              memory: 24G
            reservations:
              memory: 16G
    ports:
      - '2001:2001/udp'
      - '17777:17777/udp'
      - '19999:19999/udp'  # RCON
    volumes:  
        # mounting up gamedir to you computer to speed up container reload speed
      - ./reforger:/reforger/ # you can remove or change to a volume to keep files contained
      - './ff_config/mods_file.json:/reforger/mods_file.json' # loading mod file list
      - './ff_config/ServerAdminTools_Config.json:/home/profile/profile/ServerAdminTools_Config.json' # specific to the mod Server Admin Tool
      - './reforger/profile/profile/BaconLoadoutEditor_Loadouts/:/home/profile/profile/BaconLoadoutEditor_Loadouts/' # specific to the mod Server Admin Tool
    restart: unless-stopped # if your server keeps restarting please remove this line to stop it from doing so
    # used for unit test
    #env_file: 
    #  - ./reforger.env
    environment:
      GAME_SCENARIO_ID: '{62952497125C5F6A}Missions/FreedomFightersBaseCamp.conf' # only work when you have the Freedom Fighters scenario mod installed
      GAME_NAME: Freedom-fighters.eu/Reforger
      GAME_MODS_JSON_FILE_PATH: '/reforger/mods_file.json'
      ARMA_MAX_FPS: '60'
      GAME_SUPPORTED_PLATFORMS: 'PLATFORM_PC'
      SKIP_INSTALL: 'true'
      GAME_PASSWORD_ADMIN: /run/secrets/admin_password
      RCON_PASSWORD: /run/secrets/rcon_password
      GAME_PASSWORD: /run/secrets/user_password
secrets:
  admin_password:
    file: admin.txt
  rcon_password:
    file: rcon_password.txt
  user_password:
    file: user.txt